import React, { createContext, useContext, useEffect, useState } from "react";
import { CheckCircle2, Info, X, AlertTriangle } from "lucide-react";

export function cn(...parts: Array<string | false | null | undefined>) { return parts.filter(Boolean).join(" "); }

export function Button({ children, variant = "primary", size = "md", className = "", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger" | "outline"; size?: "sm" | "md" | "lg" }) {
  const variants = {
    primary: "bg-slate-950 text-white hover:bg-slate-800 shadow-sm",
    secondary: "bg-indigo-600 text-white hover:bg-indigo-700 shadow-sm shadow-indigo-600/20",
    ghost: "bg-transparent text-slate-600 hover:bg-slate-100",
    danger: "bg-rose-600 text-white hover:bg-rose-700 shadow-sm",
    outline: "border border-slate-200 bg-white text-slate-700 hover:border-slate-300 hover:bg-slate-50 shadow-sm",
  };
  const sizes = { sm: "h-9 px-3 text-xs", md: "h-10 px-4 text-sm", lg: "h-12 px-5 text-sm" };
  return <button {...props} className={cn("inline-flex items-center justify-center gap-2 rounded-xl font-semibold transition duration-200 focus:outline-none focus:ring-4 focus:ring-indigo-500/10 disabled:cursor-not-allowed disabled:opacity-50", variants[variant], sizes[size], className)}>{children}</button>;
}

export function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={cn("h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10", props.className)} />; }
export function Select(props: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className={cn("h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10", props.className)} />; }
export function Textarea(props: React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea {...props} className={cn("min-h-28 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10", props.className)} />; }
export function Label({ children }: { children: React.ReactNode }) { return <label className="mb-1.5 block text-xs font-bold uppercase tracking-[0.08em] text-slate-500">{children}</label>; }
export function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <div><Label>{label}</Label>{children}{hint && <p className="mt-1.5 text-[11px] text-slate-400">{hint}</p>}</div>; }
export function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={cn("rounded-2xl border border-slate-200/90 bg-white shadow-[0_8px_30px_rgba(15,23,42,.035)]", className)}>{children}</section>; }
export function Badge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "success" | "warning" | "danger" | "info" }) { const tones = { neutral: "bg-slate-100 text-slate-700", success: "bg-emerald-50 text-emerald-700 ring-1 ring-emerald-100", warning: "bg-amber-50 text-amber-700 ring-1 ring-amber-100", danger: "bg-rose-50 text-rose-700 ring-1 ring-rose-100", info: "bg-indigo-50 text-indigo-700 ring-1 ring-indigo-100" }; return <span className={cn("inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-bold tracking-wide", tones[tone])}>{children}</span>; }
export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) { return <div className="flex items-start gap-3 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-4 text-sm text-rose-700"><AlertTriangle size={18} className="mt-0.5 shrink-0"/><div className="flex-1"><p className="font-semibold">Something went wrong</p><p className="mt-1 leading-6">{message}</p>{onRetry && <Button size="sm" variant="outline" className="mt-3" onClick={onRetry}>Try again</Button>}</div></div>; }
export function EmptyState({ title, description, action }: { title: string; description?: string; action?: React.ReactNode }) { return <div className="flex min-h-[230px] flex-col items-center justify-center p-8 text-center"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-400"><Info size={20}/></div><h3 className="font-bold text-slate-900">{title}</h3>{description && <p className="mt-1 max-w-md text-sm leading-6 text-slate-500">{description}</p>}{action && <div className="mt-5">{action}</div>}</div>; }
export function Spinner({ label }: { label?: string }) { return <div className="flex items-center justify-center gap-3 text-sm text-slate-500"><span className="h-4 w-4 animate-spin rounded-full border-2 border-slate-200 border-t-indigo-600"/>{label && <span>{label}</span>}</div>; }
export function PageLoader() { return <div className="flex min-h-[420px] items-center justify-center"><Spinner label="Loading workspace…"/></div>; }
export function SectionHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div>{eyebrow && <p className="mb-1.5 text-[11px] font-extrabold uppercase tracking-[0.16em] text-indigo-600">{eyebrow}</p>}<h1 className="text-2xl font-extrabold tracking-[-.025em] text-slate-950 sm:text-3xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{description}</p>}</div>{action}</div>; }
export function StatCard({ label, value, sub, icon: Icon, tone = "indigo" }: { label: string; value: React.ReactNode; sub?: string; icon: React.ElementType; tone?: "indigo" | "emerald" | "amber" | "rose" | "sky" }) { const colors = { indigo: "bg-indigo-50 text-indigo-600", emerald: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600", rose: "bg-rose-50 text-rose-600", sky: "bg-sky-50 text-sky-600" }; return <Card className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-2 text-3xl font-extrabold tracking-tight text-slate-950">{value}</p>{sub && <p className="mt-1 text-xs text-slate-500">{sub}</p>}</div><div className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-xl", colors[tone])}><Icon size={19}/></div></div></Card>; }

const ToastContext = createContext<{ toast: (message: string, type?: "success" | "error" | "info") => void } | null>(null);
export function ToastProvider({ children }: { children: React.ReactNode }) { const [items, setItems] = useState<Array<{id:number;message:string;type:string}>>([]); useEffect(() => { if (!items.length) return; const t = window.setTimeout(() => setItems(v => v.slice(1)), 3200); return () => window.clearTimeout(t); }, [items]); const toast = (message: string, type: "success" | "error" | "info" = "success") => setItems(v => [...v, { id: Date.now() + Math.random(), message, type }]); return <ToastContext.Provider value={{ toast }}>{children}<div className="fixed bottom-5 right-5 z-[200] flex w-[min(380px,calc(100vw-2rem))] flex-col gap-2">{items.map(x => <div key={x.id} className="flex items-start gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-2xl"><div className={cn("mt-0.5", x.type === "error" ? "text-rose-600" : x.type === "info" ? "text-indigo-600" : "text-emerald-600")}><CheckCircle2 size={18}/></div><p className="flex-1 text-sm font-semibold text-slate-700">{x.message}</p><button onClick={() => setItems(v => v.filter(i => i.id !== x.id))} className="text-slate-400 hover:text-slate-700"><X size={15}/></button></div>)}</div></ToastContext.Provider>; }
export function useToast() { const c = useContext(ToastContext); if (!c) throw new Error("useToast must be used within ToastProvider"); return c; }
