import { useEffect, useState } from "react";
import type { ElementType } from "react";
import { AlertTriangle, ArrowRight, Building2, CheckCircle2, Mail, Phone, ShieldCheck, UsersRound, UserRound } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { api } from "../lib/api";
import { Badge, Button, Card, EmptyState, ErrorState, PageLoader, SectionHeader, Spinner, StatCard } from "../components/ui";

export function MentorDashboard() {
  const [data, setData] = useState<any>(null); const [error, setError] = useState("");
  const load = async () => { setError(""); try { setData(await api<any>("/mentor/dashboard")); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load mentor dashboard"); } };
  useEffect(() => { load(); }, []);
  if (!data) return <div className="min-h-[420px] flex items-center justify-center">{error ? <ErrorState message={error} onRetry={load}/> : <Spinner label="Loading mentor workspace…"/>}</div>;
  const m = data.mentor; const teams = data.teams ?? [];
  return <div className="space-y-6"><SectionHeader eyebrow="Mentor workspace" title={`Good to see you, ${m.fullName?.split(" ")[0] ?? "mentor"}.`} description="Review your guidance load, assigned teams and team readiness." action={<Badge tone={m.atCapacity ? "warning" : "success"}>{m.atCapacity ? "At capacity" : "Accepting teams"}</Badge>}/><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Assigned teams" value={`${m.assignedTeamCount}/${m.maxTeams}`} sub="Current guidance load" icon={UsersRound}/><StatCard label="Open capacity" value={m.availableCapacity} sub="Teams you can receive" icon={CheckCircle2} tone="emerald"/><StatCard label="Recommended minimum" value={m.minTeams} sub={m.belowRecommended ? "Below target" : "Within target"} icon={UserRound} tone={m.belowRecommended ? "amber" : "sky"}/></div><div className="grid gap-6 xl:grid-cols-[1fr_.38fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-6"><div><h2 className="font-extrabold">Assigned teams</h2><p className="mt-1 text-xs text-slate-500">Teams currently allocated to your guidance queue.</p></div><span className="text-xs font-bold text-slate-400">{teams.length} total</span></div>{teams.length ? <div className="grid gap-4 p-5 md:grid-cols-2">{teams.map((t: any) => <TeamCard key={t.id} team={t}/>)}</div> : <EmptyState title="No teams assigned" description="An administrator will assign eligible teams from the mentor allocation workspace."/>}</Card><Card className="p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-slate-400">Your profile</p><h2 className="mt-1 text-lg font-extrabold">Mentor details</h2><div className="mt-5 space-y-3"><Info icon={Mail} label="Email" value={m.email}/><Info icon={Phone} label="Phone" value={m.phone}/><Info icon={ShieldCheck} label="Specialization" value={m.specialization || "General mentor"}/></div><div className="mt-6 rounded-2xl bg-slate-50 p-4"><div className="flex justify-between text-xs font-bold"><span>Capacity used</span><span>{m.assignedTeamCount}/{m.maxTeams}</span></div><div className="mt-3 h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-indigo-600" style={{ width: `${m.maxTeams ? Math.min(100, m.assignedTeamCount / m.maxTeams * 100) : 0}%` }}/></div></div></Card></div></div>;
}

export function MentorTeamsPage() { const [data, setData] = useState<any>(null); const [error, setError] = useState(""); const load = async () => { try { setData(await api<any>("/mentor/dashboard")); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load teams"); } }; useEffect(() => { load(); }, []); if (!data) return <div className="min-h-[420px] flex items-center justify-center">{error ? <ErrorState message={error} onRetry={load}/> : <Spinner label="Loading teams…"/>}</div>; return <div><SectionHeader eyebrow="Guidance" title="Assigned teams" description="Review member composition, eligibility and contact details for every team you guide."/><div className="grid gap-5 lg:grid-cols-2">{(data.teams ?? []).map((team: any) => <TeamCard key={team.id} team={team} detailed/>)}{!(data.teams ?? []).length && <Card className="lg:col-span-2"><EmptyState title="No teams assigned yet"/></Card>}</div></div>; }

export function MentorTeamDetail() { const { id } = useParams(); const [data, setData] = useState<any>(null); const [error, setError] = useState(""); const navigate = useNavigate(); useEffect(() => { if (!id) return; api<any>(`/teams/${id}`).then(setData).catch(e => setError(e instanceof Error ? e.message : "Unable to load team")); }, [id]); if (error) return <div><SectionHeader eyebrow="Guidance" title="Team details"/><ErrorState message={error}/></div>; if (!data) return <PageLoader/>; const e = data.eligibility; return <div><SectionHeader eyebrow="Guidance" title={data.name} description={`${data.teamCode} · ${data.memberCount}/6 members`} action={<Button variant="outline" onClick={() => navigate("/mentor/teams")}>Back to teams</Button>}/><div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card className="overflow-hidden"><div className="border-b border-slate-100 p-6"><div className="flex items-center gap-3"><h2 className="font-extrabold">Team members</h2><Badge tone={data.isEligible ? "success" : "warning"}>{data.isEligible ? "Eligible" : "Needs action"}</Badge></div><p className="mt-1 text-xs text-slate-500">Contact and academic details for the assigned team.</p></div><div className="divide-y divide-slate-100">{(data.members ?? []).map((m: any) => <div key={m.id} className="flex items-center gap-4 p-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-xs font-black text-indigo-700">{m.fullName?.slice(0,1)}</div><div className="min-w-0 flex-1"><p className="font-bold">{m.fullName}</p><p className="mt-1 text-xs text-slate-400">{m.registerNumber} · {m.email}</p></div><div className="hidden text-right sm:block"><p className="text-xs font-bold">{m.department}</p><p className="mt-1 text-[10px] text-slate-400">{m.isLeader ? "Team leader" : "Team member"}</p></div></div>)}</div></Card><Card className="p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-slate-400">Readiness</p><h2 className="mt-1 text-lg font-extrabold">Eligibility checks</h2><div className="mt-5 space-y-3"><Check label="Members" value={`${e.memberCount}/6`} ok={e.memberCount === 6}/><Check label="Female member" value={e.femaleCount} ok={e.femaleCount >= 1}/><Check label="Departments" value={`${e.distinctDepartmentCount}/3`} ok={e.distinctDepartmentCount >= 3}/></div>{!e.isEligible && <div className="mt-5 rounded-2xl bg-amber-50 p-4 text-xs leading-6 text-amber-800"><p className="font-bold">Needs attention</p>{(e.reasons ?? []).map((r: string) => <p key={r}>• {r}</p>)}</div>}{data.mentor && <div className="mt-6 border-t border-slate-100 pt-5"><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-slate-400">Guidance mentor</p><p className="mt-2 font-bold">{data.mentor.fullName}</p></div>}</Card></div></div>; }

function TeamCard({ team, detailed = false }: { team: any; detailed?: boolean }) { const e = team.eligibility ?? {}; const navigate = useNavigate(); return <Card className="p-6"><div className="flex items-start gap-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-lg font-extrabold">{team.name}</h3><Badge tone={e.isEligible ? "success" : "warning"}>{e.isEligible ? "Eligible" : "Needs action"}</Badge></div><p className="mt-1 text-xs text-slate-400">{team.teamCode} · {team.memberCount}/6 members</p></div><button onClick={() => navigate(`/mentor/teams/${team.id}`)} className="rounded-xl p-2 text-slate-400 hover:bg-slate-50"><ArrowRight size={17}/></button></div><div className="mt-5 grid grid-cols-3 gap-2"><Check label="Members" value={`${e.memberCount}/6`} ok={e.memberCount === 6}/><Check label="Female" value={e.femaleCount} ok={e.femaleCount >= 1}/><Check label="Departments" value={e.distinctDepartmentCount} ok={e.distinctDepartmentCount >= 3}/></div>{detailed && <div className="mt-5 divide-y divide-slate-100 border-t border-slate-100">{(team.members ?? []).map((m: any) => <div key={m.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-semibold">{m.fullName}</p><p className="text-[11px] text-slate-400">{m.registerNumber}</p></div><span className="text-xs text-slate-500">{m.department}</span></div>)}</div>}{!e.isEligible && <div className="mt-4 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800"><AlertTriangle className="mr-1 inline" size={13}/>{(e.reasons ?? []).join(" ")}</div>}</Card>; }
function Check({ label, value, ok }: { label: string; value: any; ok: boolean }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-slate-400">{label}</p><p className="mt-1 text-sm font-extrabold">{value}</p><p className={ok ? "text-[10px] font-bold text-emerald-600" : "text-[10px] font-bold text-amber-600"}>{ok ? "PASS" : "ACTION"}</p></div>; }
function Info({ icon: Icon, label, value }: { icon: ElementType; label: string; value: any }) { return <div className="flex items-center gap-3 rounded-xl border border-slate-100 bg-slate-50 p-3"><Icon size={16} className="text-indigo-600"/><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-slate-400">{label}</p><p className="mt-1 truncate text-xs font-semibold text-slate-700">{value || "—"}</p></div></div>; }
